#!/usr/bin/env bash
# test 


echo "You start with $# positional parameters"
echo "aruments are $@ "
for arg in $@
do
	echo $arg
done
# Loop until all parameters are used up
while [ "$1" != "" ]; do
    echo "Parameter 1 equals $1"
    echo "You now have $# positional parameters"

    # Shift all the parameters down by one
    shift

done
