#!/usr/bin/env bash
# print "Best School" ten times with for loop

#for i in {1..10} #not used as i not used variable
#do
#	echo "Best School"
#done

for (( i=0; i<10; i++ ))
do
	echo "Best School"
done


