#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd.

#Your script should only display:

#username
#user id
#Home directory path for the user

f="/etc/passwd"
while read -r line
do
	echo "$line" | cut -d ":" -f 1,3,6
done < $f
