#!/usr/bin/env bash
# Write a Bash script that displays the visitor IP along with the HTTP status code
# from the Apache log file.

#Requirement:

#Format: IP HTTP_CODE
#in a list format
#185.130.5.207 301
#185.130.5.207 301

awk '{print $1,$9}' apache-access.log
