#!/usr/bin/env bash
# print "Best School" 10 times with while loop
# except for 9th time print hi after "best school"

i=1
while ((i <= 10))
do
	echo "Best School"
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	((i++))
done
