#!/usr/bin/env bash
# Write a Bash script that displays:

#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)

# for f in $(ls | cut -d "-" -f 2)
for f in $(find . -iname "*-*" | cut -d "-" -f 2)
do
	echo "$f"
done

