#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on.


ifconfig -a | awk '/inet/ {print $2}' | awk '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/'
