#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on.


ifconfig -a | awk '/inet/ {print $2}' | awk '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/'

# soution 2
# ifconfig -a | awk '/inet\s+[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ {print $2}'

# solution 3
# interfaces=$(ifconfig -a | grep 'inet ' | awk '{print $2}')

# Loop through each interface and extract the IPv4 addresses
#for ip in $interfaces; do
  # Check if the IP is in the format of an IPv4 address
#  if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
#    echo "$ip"
#  fi
#done
